version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.36:2181"  # Use the service name as the hostname
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.36:9092"  # Use the service name as the hostname
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper